### ISSUE TITLE
Bitdefender claims Java.Trojan.GenericGBA.33263 in Fields.class

### ISSUE THREAD

**Issue by xcruell** [Lenni0451/Reflect#3]
Hi,
i downloaded Create: Astral a few days ago and Bitdefender keeps deleting that one mod: .minecraft.fabric\processedMods\net_lenni0451_reflect-1.1.0-658b0f614e510689.jar => net/lenni0451/reflect/Fields.class
and claims it is infected with Java.Trojan.GenericGBA.33263..
I uploaded it to virustotal giving me a 0/61 result, but how come bitdefender desperately removes it, even after adding it as an exception..
It's the only mod i ever saw giving me such a warning.
VT Link: https://www.virustotal.com/gui/file/30c9d2f9bea0aac7fe697bfadb2121de257e5936674550d8203798fbef1c1780

Regards

**Comment by Lenni0451** [comment]
Hi, there are numerous reports of Bitdefender starting to false flag Reflect for no reason. I'm currently not sure how I would fix this. I'll let you know if there is a solution

**Comment by RealTriassic** [comment]
> Hi, there are numerous reports of Bitdefender starting to false flag Reflect for no reason. I'm currently not sure how I would fix this. I'll let you know if there is a solution

You can report a false positive to Bitdefender [right here](https://www.bitdefender.com/consumer/support/answer/29358/) then they'll either fix it or explain why it is not a false positive.

**Comment by NolanHewitt** [comment]
Google also auto flags mods using this as a virus. I use google drive to share a collection of mods and config files privately between a few friends, and google sent me an auto email threatening to ban my drive account because of the false detection.

**Comment by Lenni0451** [comment]
> Google also auto flags mods using this as a virus. I use google drive to share a collection of mods and config files privately between a few friends, and google sent me an auto email threatening to ban my drive account because of the false detection.

It would be good if you could report this to google to review. Maybe they will realize that it is a false flag and fix it

**Comment by Lenni0451** [comment]
> Hi,
> i downloaded Create: Astral a few days ago and Bitdefender keeps deleting that one mod: .minecraft.fabric\processedMods\net_lenni0451_reflect-1.1.0-658b0f614e510689.jar => net/lenni0451/reflect/Fields.class
> and claims it is infected with Java.Trojan.GenericGBA.33263..
> I uploaded it to virustotal giving me a 0/61 result, but how come bitdefender desperately removes it, even after adding it as an exception..
> It's the only mod i ever saw giving me such a warning.
> VT Link: https://www.virustotal.com/gui/file/30c9d2f9bea0aac7fe697bfadb2121de257e5936674550d8203798fbef1c1780
> 
> 
> Regards

It has now been over a week since I wrote the Bitdefender support and I still have'nt gotten a response so there is sadly nothing I can do about this
